import type { Metadata } from "next";
import { Inter, Hanken_Grotesk } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const hk_grotesk = Hanken_Grotesk({  subsets: ['latin'],
});
import {NextUIProvider} from "@nextui-org/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={hk_grotesk.className}>
      <NextUIProvider>
          {children}
      </NextUIProvider>
      </body>
    </html>
  );
}
